#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=6GB
#SBATCH --time=1:00:00
#SBATCH --account=jpwalter_148

module purge
module load gcc/8.3.0
#module load python/3.7

#conda init bash
conda activate EdgePipe
# test ViT Base
python3 get_distribution.py -pt $1 -q $2,$2 -p -o /home1/haonanwa/projects/EdgePipe/results/dist_imgs_log_theoratical_clamp

# test ViT Large
# python3 evaluation.py -pt $1 -q $2,$2 -m google/vit-large-patch16-224
